### ISSUE TITLE
Should we start this up in 2018-2019?

### ISSUE THREAD

**Issue by jmarca** [WSOCcodingclub/meetings#2]
If there is interest I can be advisor. Would like to aim more towards student driven rather than me driven. Any opinions @piastorms and @carligracej ?

**Comment by piastorms** [comment]
Hello, this semester is quite busy for me due to college applications. I think I'm going to focus on that for right now! Thanks for everything! :) 

-Pia Cano

**Comment by jmarca** [comment]
Remember that "president of coding club" looks good on college apps...

**Comment by carligracej** [comment]
I think coding club is so fun and could get a lot of student interest this year. I don’t think I will be able to commit this year (or at least first semester) because I have SAT prep and a job, but I can absolutely ask around and connect anyone with interest to you or any other members!

**Comment by jmarca** [comment]
Okay, I'll ping Mr. Pitts.
